### ISSUE TITLE
Rewrite in more obscure languages

### ISSUE THREAD

**Issue by 3ygun** [J3RN/advent-of-code#1]
J3RN,

I write to you today requesting that you utilize [Brainfuck](https://en.wikipedia.org/wiki/Brainfuck) as the next language of choice for solving these problems. Why? Because you already have such elegant functional pros and symbols why not switch to full symbols?

Sincerely,
David

P.S. Hope life is going well!

**Comment by J3RN** [comment]
@3ygun Hey, good to hear from you! This is a phenomenal idea. I'm not sure if you've seen or not, but I've actually been working on a Brainfuck interpreter known as [JBI](https://github.com/J3RN/jbi). That project has been dormant for a couple months, but it would be great to dust it off for this purpose.

Cheers! :beers:

**Comment by 3ygun** [comment]
🤣 of course. Glad you're also doing well! And congrats on the I assume remote role at Joyride. Glad you're getting to stay in Elixir land. Cheers 🍻
